### ISSUE TITLE
Serious crash with some parameters

### ISSUE THREAD

**Issue by retrue** [nextbreakpoint/nextfractal#19]
Yesterday I was playing with Nextfractal, tinkering with the parameters of one of the examples, this one:
![Sin título](https://user-images.githubusercontent.com/18194241/64161371-d4cc5a80-ce3d-11e9-806f-49b5e9a48b8d.png)

I know nothing about programmation, or M Language, but I am an advanced user with experience with fractal software.
I modified the formula after Loop to this: x = x * x * x * x * x * x - w; to get an hexagon.
I tinkered with more parameters without problems. And then I tried different valours in the palette gradient part. I tried very low and very high valours.
In this part:
		palette gradient {
			[#FCFF0A0A > #FFFFFFFF, 4];
			[#CEFFFFFF > #FF0042A9, 500];
			[#FF0042A9 > #FF000000, 2];

If I changed one of those numbers on the right to very very very high valours the program turns unresponsive, then the graphic card driver crashes and seconds after that I get a Blue Screen Of Death. After 4 BSOD in twenty minutes I decided to stop introducing very high numbers.

My computer is an Intel 4770, 16 GB RAM, GeForce GTX 1060 6GB, with Windows 10 Pro and the last Nvidia drivers.

**Comment by nextbreakpoint** [comment]
Sorry I can't reproduce the error. I believe it could be a problem related to the amount of memory used, but it might also be caused by other reasons. NextFractal doesn't currently check the size of the allocated palette. It should not cause a Blue Screen Of Death, but instead it should cause an exception.
